[pytest]
# 1. 自动添加参数 (精简 addopts)
# -s: 确保 print() 实时输出
# -v: 详细模式
# -p no:logging : 如果你有其他插件冲突，可以尝试禁用再开启，但通常不用
addopts = -vv -s -x
timeout = 360

# 2. 核心路径限制
testpaths = backend/tests
python_files = test_*.py
norecursedirs = .git __pycache__ node_modules postgres_data venv .venv /mnt/c *AppData*

# 3. Python路径配置
pythonpath = backend

# 3. 实时日志 (Live Logging) 强化配置
log_cli = true
# 建议同时设置全局日志级别，确保 INFO 信号能通过
log_level = INFO
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

filterwarnings =
    ignore::UserWarning:py_mini_racer.*