#!/usr/bin/env python3
"""
Single Tushare call entrypoint for LLM-generated parameters.

The LLM should read SKILL.md/references, choose the Tushare interface, then pass:
{
  "interface_name": "daily",
  "params": {
    "ts_code": "000001.SZ",
    "start_date": "20240101",
    "end_date": "20240131"
  }
}
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any


def build_tushare_client() -> Any:
    """Build a Tushare pro client from environment variables."""
    import tushare as ts

    api_url = os.environ.get("TUSHARE_API", "").strip()
    token = os.environ.get("TUSHARE_TOKEN", "").strip()
    if api_url:
        from tushare.pro.client import DataApi

        DataApi._DataApi__http_url = api_url
    if not token:
        raise ValueError("TUSHARE_TOKEN is not configured")
    return ts.pro_api(token)


def parse_json_object(raw_payload: str, source: str) -> dict[str, Any]:
    """Parse a JSON object from text."""
    payload = json.loads(raw_payload)
    if not isinstance(payload, dict):
        raise ValueError(f"{source} JSON payload must be an object.")
    return payload


def require_interface_name(payload: dict[str, Any]) -> str:
    """Read the required Tushare interface name."""
    value = payload.get("interface_name")
    if not isinstance(value, str) or not value.strip():
        raise ValueError("interface_name is required and must be a non-empty string.")
    return value.strip()


def read_params(payload: dict[str, Any]) -> dict[str, Any]:
    """Read Tushare kwargs generated by the LLM."""
    params = payload.get("params", {})
    if not isinstance(params, dict):
        raise ValueError("params must be an object.")
    return params


def read_payload() -> dict[str, Any]:
    """Read the LLM-generated payload from argv or stdin."""
    parser = argparse.ArgumentParser(description="Call one Tushare interface.")
    parser.add_argument("payload", nargs="?", help="JSON object with interface_name and params.")
    parser.add_argument("--interface-name", dest="interface_name")
    parser.add_argument("--params-json", dest="params_json", default="{}")
    args = parser.parse_args()

    if args.payload:
        return parse_json_object(args.payload, "argv payload")

    if args.interface_name:
        return {
            "interface_name": args.interface_name,
            "params": parse_json_object(args.params_json, "--params-json"),
        }

    raw_stdin = sys.stdin.read().strip()
    if raw_stdin:
        return parse_json_object(raw_stdin, "stdin")

    raise ValueError("Provide stdin JSON, argv JSON, or --interface-name with optional --params-json.")


def sanitize_scalar(value: Any) -> Any:
    """Convert scalar values into JSON-safe values."""
    if value is None:
        return None
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if isinstance(value, (str, int, float, bool, dict, list)):
        return value
    return str(value)


def serialize_result(result: Any) -> dict[str, Any]:
    """Serialize a Tushare result without row truncation."""
    try:
        import pandas as pd
    except ImportError:
        pd = None

    if pd is not None and isinstance(result, pd.DataFrame):
        safe_df = result.where(result.notna(), None)
        rows = [{key: sanitize_scalar(value) for key, value in row.items()} for row in safe_df.to_dict("records")]
        return {
            "type": "dataframe",
            "columns": list(safe_df.columns),
            "rows": rows,
            "row_count": len(rows),
        }

    if pd is not None and isinstance(result, pd.Series):
        return {"type": "series", "data": {key: sanitize_scalar(value) for key, value in result.to_dict().items()}}

    if isinstance(result, list):
        return {
            "type": "list",
            "rows": [item if isinstance(item, dict) else sanitize_scalar(item) for item in result],
            "row_count": len(result),
        }

    if isinstance(result, dict):
        return {"type": "dict", "data": {key: sanitize_scalar(value) for key, value in result.items()}}

    return {"type": "scalar", "data": sanitize_scalar(result)}


def call_tushare(interface_name: str, params: dict[str, Any]) -> dict[str, Any]:
    """Call one Tushare interface through the standalone Tushare SDK client."""
    pro_client = build_tushare_client()
    func_obj = getattr(pro_client, interface_name, None)
    if callable(func_obj):
        result = func_obj(**params)
    else:
        result = pro_client.query(interface_name, **params)
    return serialize_result(result)


def main() -> int:
    """CLI entrypoint."""
    try:
        payload = read_payload()
        interface_name = require_interface_name(payload)
        params = read_params(payload)
        result = call_tushare(interface_name, params)
        sys.stdout.write(
            json.dumps(
                {
                    "success": True,
                    "provider": "tushare",
                    "interface_name": interface_name,
                    "params": params,
                    "result": result,
                },
                ensure_ascii=False,
            )
        )
        sys.stdout.write("\n")
        return 0
    except Exception as exc:
        sys.stdout.write(json.dumps({"success": False, "error": str(exc)}, ensure_ascii=False))
        sys.stdout.write("\n")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
